import "./style.css";
import { generateIdentity, loadIdentity, saveIdentity } from "./character";
import { horrorEvents, trial, availableTrialChoices } from "./events";
import { Network, roomCode, validCode } from "./network";
import { render, VIEW_H, VIEW_W } from "./render";
import { isBlocked, npcs, phaseAt, regions } from "./world";
import type { Direction, Identity, Player, WorldState } from "./types";

const app=document.querySelector<HTMLDivElement>("#app")!; let identity=loadIdentity();
let net:Network|undefined,me:Player,players:Player[]=[],world:WorldState={startedAt:Date.now(),timeOffset:0,timeScale:1,paused:false,sharedEvents:[],storyFlags:[]};
let modalOpen=false,lastMove=0,hallucinationSeen=false,trialDone=false,audio:AudioContext|undefined;
const color=()=>["#d24d57","#54aeb0","#d5a94d","#8469c2"][Math.floor(Math.random()*4)];

function home(){app.innerHTML=`<section class="title-screen"><div class="moon"></div><div class="logo"><small>影</small><h1>KAGE</h1><p>SHADOWS REMEMBER</p></div><div class="menu"><button id="create">CREATE ROOM</button><button id="join">JOIN ROOM</button><button class="quiet" id="identity">VIEW WANDERER</button></div><p class="hint">A quiet multiplayer tale for 2–8 lost souls<br>Headphones recommended</p></section>`;
 document.querySelector("#create")!.addEventListener("click",()=>enter(roomCode()));document.querySelector("#join")!.addEventListener("click",joinDialog);document.querySelector("#identity")!.addEventListener("click",()=>profile(true));}
function joinDialog(){overlay(`<h2>JOIN THE OTHERS</h2><p>Enter the four letters they gave you.</p><input id="code" maxlength="4" inputmode="text" autocomplete="off" placeholder="YAMI"><div class="row"><button id="go">ENTER</button><button id="cancel">BACK</button></div>`,()=>{const input=document.querySelector<HTMLInputElement>("#code")!;input.addEventListener("input",()=>input.value=input.value.toUpperCase().replace(/[^A-Z]/g,""));document.querySelector("#go")!.addEventListener("click",()=>validCode(input.value)?enter(input.value):toast("A room code is four letters."));document.querySelector("#cancel")!.addEventListener("click",closeOverlay);input.focus()});}
function enter(code:string){const id=sessionStorage.getItem("kage-session")||crypto.randomUUID();sessionStorage.setItem("kage-session",id);me={id,name:identity.archetype.split(" ").at(-1)!,x:regions.village.spawn[0],y:regions.village.spawn[1],region:"village",direction:"down",moving:false,health:100,identity,color:color()};
 app.innerHTML=`<section id="game"><canvas width="${VIEW_W}" height="${VIEW_H}"></canvas><header><div><b>${code}</b><span>ROOM</span></div><button id="profile">☰</button></header><div id="notice"></div><div id="dialogue"></div><div class="mobile-controls"><div class="dpad"><button data-dir="up">▲</button><button data-dir="left">◀</button><button data-dir="down">▼</button><button data-dir="right">▶</button></div><div class="actions"><button id="b">B</button><button id="a">A</button></div></div><footer><span id="region">Hollow Village</span><div class="health"><i></i></div><span id="virtues">W${identity.wisdom} · C${identity.courage} · ♥${identity.compassion}</span></footer></section>`;
 net=new Network(code,me);net.connect(m=>{if(m.type==="state"){players=m.players;world=m.world;const authoritative=players.find(p=>p.id===me.id);if(authoritative)Object.assign(me,authoritative);}else if(m.type==="error")toast(m.message)});bindControls();profile(false);requestAnimationFrame(loop);}
function bindControls(){document.querySelector("#profile")!.addEventListener("click",()=>profile(true));document.querySelector("#a")!.addEventListener("pointerdown",interact);document.querySelector("#b")!.addEventListener("pointerdown",closeOverlay);document.querySelectorAll<HTMLElement>("[data-dir]").forEach(b=>b.addEventListener("pointerdown",e=>{e.preventDefault();move(b.dataset.dir as Direction)}));window.addEventListener("keydown",keys);window.addEventListener("beforeunload",()=>net?.close());}
function keys(e:KeyboardEvent){if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight","w","a","s","d","e","Enter","Escape"].includes(e.key))e.preventDefault();if(modalOpen){if(e.key==="Escape")closeOverlay();return}const d:Record<string,Direction>={ArrowUp:"up",w:"up",ArrowDown:"down",s:"down",ArrowLeft:"left",a:"left",ArrowRight:"right",d:"right"};if(d[e.key])move(d[e.key]);if(e.key==="e"||e.key==="Enter")interact();}
function move(direction:Direction){if(modalOpen||performance.now()-lastMove<105)return;lastMove=performance.now();const delta={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[direction];let x=me.x+delta[0],y=me.y+delta[1];const exit=regions[me.region].exits.find(e=>e.x===x&&e.y===y);if(exit){me.region=exit.to;me.x=exit.tx;me.y=exit.ty;toast(regions[me.region].name);checkStory();}else if(!isBlocked(me.region,x,y)){me.x=x;me.y=y;checkStory();}me.direction=direction;net?.send({type:"move",x:me.x,y:me.y,region:me.region,direction});}
function adjacent(x:number,y:number){return Math.abs(me.x-x)+Math.abs(me.y-y)<=1;}
function interact(){startAudio();const npc=npcs.find(n=>n.region===me.region&&adjacent(n.x,n.y));if(npc){dialogue(npc.name,npc.text);return}if(me.region==="village"&&adjacent(10,8)){campfire();return}if(me.region==="river"&&!trialDone&&me.x>8){showTrial();return}dialogue("Your thoughts",identity.burden==="Guilt"?"The earth remembers a footprint you do not.":"For a moment, your shadow points the wrong way.");}
function checkStory(){const phase=currentPhase();for(const ev of horrorEvents)if(ev.region===me.region&&ev.visible(identity,phase,world.sharedEvents)&&!hallucinationSeen){hallucinationSeen=true;setTimeout(()=>dialogue(ev.stage==="PRIVATE"?"Only you can see this":"All of you see this",ev.text),250);}if(me.region==="bamboo"&&hallucinationSeen&&identity.corruption>=2&&!world.sharedEvents.includes("watcher-shared"))net?.send({type:"event",id:"watcher-shared"});if(me.region==="river"&&me.x>9&&!trialDone)showTrial();}
function showTrial(){trialDone=true;const choices=availableTrialChoices(players).map((c,i)=>`<button data-choice="${i}">${c.label}${c.need?` <small>${c.need}</small>`:""}</button>`).join("");overlay(`<h2>${trial.title}</h2><p>${trial.setup}</p><div class="choices">${choices}</div>`,()=>document.querySelectorAll<HTMLElement>("[data-choice]").forEach(b=>b.onclick=()=>{const c=availableTrialChoices(players)[Number(b.dataset.choice)];(identity as any)[c.effect]++;identity.flags.push(`trial:${c.effect}`);saveIdentity(identity);closeOverlay();dialogue("The Guardian",c.effect==="compassion"?"It uncovers a sleeping child. She knows your name.":"The river stills. Something beneath it changes its mind.")}));}
function campfire(){overlay(`<h2>THE CAMPFIRE</h2><p>The flames lean toward you, waiting for a truth.</p><div class="choices"><button data-fire="truth">Reveal a memory</button><button data-fire="lie">Tell a comforting lie</button><button data-fire="silent">Remain silent</button></div>`,()=>document.querySelectorAll<HTMLElement>("[data-fire]").forEach(b=>b.onclick=()=>{const choice=b.dataset.fire!;if(choice==="truth"){identity.compassion++;identity.memories.push(`A bell beneath the ${identity.seed.split("-")[0]}.`)}if(choice==="lie")identity.corruption++;if(choice==="silent")identity.courage++;saveIdentity(identity);closeOverlay();toast("The others will remember your choice.")}));}
function die(){identity.deaths++;identity.corruption+=1;identity.memories.push("You remember dying where you have never been.");saveIdentity(identity);me.health=100;me.region="village";[me.x,me.y]=regions.village.spawn;dialogue("DEATH IS NOT AN END",`The campfire returns you. Death ${identity.deaths}: reality grows less certain.`);}
function profile(open:boolean){if(!open){setTimeout(()=>dialogue("A FRAGMENT OF YOU",`You are a ${identity.archetype}. ${identity.burden} follows close behind. Use WASD or the D-pad. Find the village fire.`),300);return}overlay(`<h2>${identity.archetype.toUpperCase()}</h2><p class="burden">BURDEN · ${identity.burden}</p><div class="stats"><span>WISDOM <b>${identity.wisdom}</b></span><span>COURAGE <b>${identity.courage}</b></span><span>COMPASSION <b>${identity.compassion}</b></span><span>CORRUPTION <b>${identity.corruption}</b></span></div><p>Abilities: ${identity.abilities.join(" · ")}</p><p class="fragment">Memory fragment: “${identity.memories.at(-1)||"A bell. Wet footprints. Someone calling your old name."}”</p><div class="row"><button id="resume">RETURN</button><button id="reroll">NEW SOUL</button></div>`,()=>{document.querySelector("#resume")!.addEventListener("click",closeOverlay);document.querySelector("#reroll")!.addEventListener("click",()=>{identity=generateIdentity();saveIdentity(identity);closeOverlay();home()})});}
function dialogue(name:string,text:string){const box=document.querySelector<HTMLDivElement>("#dialogue");if(!box)return;box.innerHTML=`<b>${name}</b><p>${text}</p><small>A / ENTER TO CLOSE</small>`;box.classList.add("show");modalOpen=true;const close=()=>{box.classList.remove("show");modalOpen=false;box.onclick=null};box.onclick=close;setTimeout(()=>window.addEventListener("keydown",e=>(e.key==="Enter"||e.key==="e")&&close(),{once:true}),0);}
function overlay(html:string,ready?:()=>void){let el=document.querySelector<HTMLDivElement>("#overlay");if(!el){el=document.createElement("div");el.id="overlay";document.body.append(el)}el.innerHTML=`<div class="panel">${html}</div>`;el.classList.add("show");modalOpen=true;ready?.();}
function closeOverlay(){document.querySelector("#overlay")?.classList.remove("show");modalOpen=false;}
function toast(s:string){const n=document.querySelector<HTMLDivElement>("#notice");if(!n)return;n.textContent=s;n.classList.add("show");setTimeout(()=>n.classList.remove("show"),1800);}
function currentMinutes(){return ((Date.now()-world.startedAt)/60000*world.timeScale+world.timeOffset)%20}function currentPhase(){return phaseAt(currentMinutes())}function clock(){const m=currentMinutes();return `${String(Math.floor((m/20)*24)).padStart(2,"0")}:${String(Math.floor(((m/20)*24%1)*60)).padStart(2,"0")}`}
function loop(t:number){if(!document.querySelector("#game"))return;const canvas=document.querySelector<HTMLCanvasElement>("canvas")!,ctx=canvas.getContext("2d")!;render(ctx,me.region,players.length?players:[me],me,currentPhase(),clock(),t);document.querySelector("#region")!.textContent=regions[me.region].name;(document.querySelector(".health i") as HTMLElement).style.width=`${me.health}%`;if(me.health<=0)die();requestAnimationFrame(loop);}
function startAudio(){if(audio)return;audio=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.type="sine";o.frequency.value=110;g.gain.value=.012;o.connect(g).connect(audio.destination);o.start();setTimeout(()=>{g.gain.exponentialRampToValueAtTime(.0001,audio!.currentTime+1.5);o.stop(audio!.currentTime+1.6)},10);}
home();
